epharmacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainweb.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainweb/urls.py
from django.urls import path
from . import views

app_name = "mainweb"
urlpatterns = [
    path("", views.homeView, name="home"),
    path("shop", views.shopView, name="shop"),
    path("single", views.singleView, name="single"),
    path("cart", views.CartView, name="cart"),
    path("checkout", views.checkOutView, name="checkout"),
    path("thanks", views.thanksView, name="thanks"),
    path("about-us", views.aboutView, name="aboutus"),
    path("contact-us", views.contactView, name="contact")
]

mainweb/models.py
from django.db import models

# Create your models here.

mainweb/views.py
from django.shortcuts import render

# Create your views here.


def shopView(request):

    return render(request, "mainweb/shop.html")

def singleView(request):

    return render(request, "mainweb/single.html")

def CartView(request):

    return render(request, "mainweb/cart.html")

def checkOutView(request):

    return render(request, "mainweb/checkout.html")

def thanksView(request):

    return render(request, "mainweb/thankyou.html")




def homeView(request):

    return render(request, "mainweb/index.html")


def aboutView(request):

    return render(request, "mainweb/about.html")


def contactView(request):

    return render(request, "mainweb/contact.html")

mainweb/templates/mainweb/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="site-blocks-cover inner-page" style="background-image: url('{% static "images/hero_1.jpg" %}');">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto align-self-center">
          <div class=" text-center">
            <h1>About Us</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum obcaecati natus iure voluptatum eveniet harum recusandae ducimus saepe.</p>ˀ
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6">
          <div class="block-16">
            <figure>
              <img src="{% static 'images/bg_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span
                  class="icon-play"></span></a>
            </figure>
          </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5">
          <div class="site-section-heading pt-3 mb-4">
            <h2 class="text-black">How We Started</h2>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo
            exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat
            asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
          <p>Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam
            cumque recusandae, laudantium minima repellendus.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 order-md-2">
          <div class="block-16">
            <figure>
              <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span
                  class="icon-play"></span></a>
  
            </figure>
          </div>
        </div>
        <div class="col-md-5 mr-auto">
  
  
          <div class="site-section-heading pt-3 mb-4">
            <h2 class="text-black">We Are Trusted Company</h2>
          </div>
          <p class="text-black">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo
            exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat
            asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
          <p class="text-black">Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam
            cumque recusandae, laudantium minima repellendus.</p>
  
        </div>
      </div>
    </div>
  </div>

  <div class="site-section site-section-sm site-blocks-1 border-0" data-aos="fade">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
          <div class="icon mr-4 align-self-start">
            <span class="icon-truck text-primary"></span>
          </div>
          <div class="text">
            <h2>Free Shipping</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
              tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
          <div class="icon mr-4 align-self-start">
            <span class="icon-refresh2 text-primary"></span>
          </div>
          <div class="text">
            <h2>Free Returns</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
              tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
          <div class="icon mr-4 align-self-start">
            <span class="icon-help text-primary"></span>
          </div>
          <div class="text">
            <h2>Customer Support</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
              tincidunt fringilla.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 site-section-heading text-center pt-4">
          <h2>The Team</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-6 mb-5">
  
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Elizabeth Graham</h3>
                <p class="block-38-subheading">CEO/Co-Founder</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio
                  recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6 mb-5">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'images/person_2.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Jennifer Greive</h3>
                <p class="block-38-subheading">Co-Founder</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio
                  recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6 mb-5">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Patrick Marx</h3>
                <p class="block-38-subheading">Marketing</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio
                  recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6 mb-5">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Mike Coolbert</h3>
                <p class="block-38-subheading">Sales Manager</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio
                  recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  

{% endblock %}

mainweb/templates/mainweb/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="bg-light py-3">
        <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
            <a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> 
            <strong class="text-black">Cart</strong>
            </div>
        </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
          <div class="row mb-5">
            <form class="col-md-12" method="post">
              <div class="site-blocks-table">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th class="product-thumbnail">Image</th>
                      <th class="product-name">Product</th>
                      <th class="product-price">Price</th>
                      <th class="product-quantity">Quantity</th>
                      <th class="product-total">Total</th>
                      <th class="product-remove">Remove</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td class="product-thumbnail">
                        <img src="{% static 'images/product_02.png' %}" alt="Image" class="img-fluid">
                      </td>
                      <td class="product-name">
                        <h2 class="h5 text-black">Ibuprofen</h2>
                      </td>
                      <td>$55.00</td>
                      <td>
                        <div class="input-group mb-3" style="max-width: 120px;">
                          <div class="input-group-prepend">
                            <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                          </div>
                          <input type="text" class="form-control text-center" value="1" placeholder=""
                            aria-label="Example text with button addon" aria-describedby="button-addon1">
                          <div class="input-group-append">
                            <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                          </div>
                        </div>
      
                      </td>
                      <td>$49.00</td>
                      <td><a href="#" class="btn btn-primary height-auto btn-sm">X</a></td>
                    </tr>
      
                    <tr>
                      <td class="product-thumbnail">
                        <img src="{% static 'images/product_01.png' %}" alt="Image" class="img-fluid">
                      </td>
                      <td class="product-name">
                        <h2 class="h5 text-black">Bioderma</h2>
                      </td>
                      <td>$49.00</td>
                      <td>
                        <div class="input-group mb-3" style="max-width: 120px;">
                          <div class="input-group-prepend">
                            <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                          </div>
                          <input type="text" class="form-control text-center" value="1" placeholder=""
                            aria-label="Example text with button addon" aria-describedby="button-addon1">
                          <div class="input-group-append">
                            <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                          </div>
                        </div>
      
                      </td>
                      <td>$49.00</td>
                      <td><a href="#" class="btn btn-primary height-auto btn-sm">X</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </form>
          </div>
      
          <div class="row">
            <div class="col-md-6">
              <div class="row mb-5">
                <div class="col-md-6 mb-3 mb-md-0">
                  <button class="btn btn-primary btn-md btn-block">Update Cart</button>
                </div>
                <div class="col-md-6">
                  <button class="btn btn-outline-primary btn-md btn-block">Continue Shopping</button>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <label class="text-black h4" for="coupon">Coupon</label>
                  <p>Enter your coupon code if you have one.</p>
                </div>
                <div class="col-md-8 mb-3 mb-md-0">
                  <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-md px-4">Apply Coupon</button>
                </div>
              </div>
            </div>
            <div class="col-md-6 pl-5">
              <div class="row justify-content-end">
                <div class="col-md-7">
                  <div class="row">
                    <div class="col-md-12 text-right border-bottom mb-5">
                      <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-md-6">
                      <span class="text-black">Subtotal</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">$230.00</strong>
                    </div>
                  </div>
                  <div class="row mb-5">
                    <div class="col-md-6">
                      <span class="text-black">Total</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">$230.00</strong>
                    </div>
                  </div>
      
                  <div class="row">
                    <div class="col-md-12">
                    <a class="btn btn-primary btn-lg btn-block" href="{% url 'mainweb:checkout' %}">Proceed To Checkout</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

mainweb/templates/mainweb/shop.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="bg-light py-3">
        <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Store</strong></div>
        </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-6">
              <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Price</h3>
              <div id="slider-range" class="border-primary"></div>
              <input type="text" name="text" id="amount" class="form-control border-0 pl-0 bg-white" disabled="" />
            </div>
            <div class="col-lg-6">
              <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Reference</h3>
              <button type="button" class="btn btn-secondary btn-md dropdown-toggle px-4" id="dropdownMenuReference"
                data-toggle="dropdown">Reference</button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                <a class="dropdown-item" href="#">Relevance</a>
                <a class="dropdown-item" href="#">Name, A to Z</a>
                <a class="dropdown-item" href="#">Name, Z to A</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Price, low to high</a>
                <a class="dropdown-item" href="#">Price, high to low</a>
              </div>
            </div>
          </div>
      
          <div class="row">
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <span class="tag">Sale</span>
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_06.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Bioderma</a></h3>
              <p class="price"><del>95.00</del> &mdash; $55.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_01.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Chanca Piedra</a></h3>
              <p class="price">$70.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_02.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Umcka Cold Care</a></h3>
              <p class="price">$120.00</p>
            </div>
      
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
      
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_03.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Cetyl Pure</a></h3>
              <p class="price"><del>45.00</del> &mdash; $20.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_05.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">CLA Core</a></h3>
              <p class="price">$38.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <span class="tag">Sale</span>
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_05.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Poo Pourri</a></h3>
              <p class="price"><del>$89</del> &mdash; $38.00</p>
            </div>
  
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <span class="tag">Sale</span>
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_01.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Bioderma</a></h3>
              <p class="price"><del>95.00</del> &mdash; $55.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}l"> <img src="{% static 'images/product_02.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Chanca Piedra</a></h3>
              <p class="price">$70.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_02.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Umcka Cold Care</a></h3>
              <p class="price">$120.00</p>
            </div>
            
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
            
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_04.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Cetyl Pure</a></h3>
              <p class="price"><del>45.00</del> &mdash; $20.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_05.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">CLA Core</a></h3>
              <p class="price">$38.00</p>
            </div>
            <div class="col-sm-6 col-lg-4 text-center item mb-4">
              <span class="tag">Sale</span>
              <a href="{% url 'mainweb:single' %}"> <img src="{% static 'images/product_06.png'  %}" alt="Image"></a>
              <h3 class="text-dark"><a href="{% url 'mainweb:single' %}">Poo Pourri</a></h3>
              <p class="price"><del>$89</del> &mdash; $38.00</p>
            </div>
          </div>
          <div class="row mt-5">
            <div class="col-md-12 text-center">
              <div class="site-block-27">
                <ul>
                  <li><a href="#">&lt;</a></li>
                  <li class="active"><span>1</span></li>
                  <li><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#">4</a></li>
                  <li><a href="#">5</a></li>
                  <li><a href="#">&gt;</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

mainweb/templates/mainweb/single.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="bg-light py-3">
        <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <a
                href="shop.html">Store</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Ibuprofen Tablets, 200mg</strong></div>
        </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
          <div class="row">
            <div class="col-md-5 mr-auto">
              <div class="border text-center">
                <img src="{% static 'images/product_07_large.png' %}" alt="Image" class="img-fluid p-5">
              </div>
            </div>
            <div class="col-md-6">
              <h2 class="text-black">Ibuprofen Tablets, 200mg</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur, vitae, explicabo? Incidunt facere, natus
                soluta dolores iusto! Molestiae expedita veritatis nesciunt doloremque sint asperiores fuga voluptas,
                distinctio, aperiam, ratione dolore.</p>
              
  
              <p><del>$95.00</del>  <strong class="text-primary h4">$55.00</strong></p>
  
              
              
              <div class="mb-5">
                <div class="input-group mb-3" style="max-width: 220px;">
                  <div class="input-group-prepend">
                    <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                  </div>
                  <input type="text" class="form-control text-center" value="1" placeholder=""
                    aria-label="Example text with button addon" aria-describedby="button-addon1">
                  <div class="input-group-append">
                    <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                  </div>
                </div>
      
              </div>
              <p><a href="{% url 'mainweb:cart' %}" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Cart</a></p>
  
              <div class="mt-5">
                <ul class="nav nav-pills mb-3 custom-pill" id="pills-tab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab"
                      aria-controls="pills-home" aria-selected="true">Ordering Information</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab"
                      aria-controls="pills-profile" aria-selected="false">Specifications</a>
                  </li>
              
                </ul>
                <div class="tab-content" id="pills-tabContent">
                  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                    <table class="table custom-table">
                      <thead>
                        <th>Material</th>
                        <th>Description</th>
                        <th>Packaging</th>
                      </thead>
                      <tbody>
                        <tr>
                          <th scope="row">OTC022401</th>
                          <td>Pain Management: Acetaminophen PM Extra-Strength Caplets, 500 mg, 100/Bottle</td>
                          <td>1 BT</td>
                        </tr>
                        <tr>
                          <th scope="row">OTC022401</th>
                          <td>Pain Management: Acetaminophen PM Extra-Strength Caplets, 500 mg, 100/Bottle</td>
                          <td>144/CS</td>
                        </tr>
                        <tr>
                          <th scope="row">OTC022401</th>
                          <td>Pain Management: Acetaminophen PM Extra-Strength Caplets, 500 mg, 100/Bottle</td>
                          <td>1 EA</td>
                        </tr>
                        
                      </tbody>
                    </table>
                  </div>
                  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
              
                    <table class="table custom-table">
              
                      <tbody>
                        <tr>
                          <td>HPIS CODE</td>
                          <td class="bg-light">999_200_40_0</td>
                        </tr>
                        <tr>
                          <td>HEALTHCARE PROVIDERS ONLY</td>
                          <td class="bg-light">No</td>
                        </tr>
                        <tr>
                          <td>LATEX FREE</td>
                          <td class="bg-light">Yes, No</td>
                        </tr>
                        <tr>
                          <td>MEDICATION ROUTE</td>
                          <td class="bg-light">Topical</td>
                        </tr>
                      </tbody>
                    </table>
              
                  </div>
              
                </div>
              </div>
  
      
            </div>
          </div>
        </div>
      </div>
  
      <div class="site-section bg-secondary bg-image" style="background-image: url('images/bg_2.jpg');">
        <div class="container">
          <div class="row align-items-stretch">
            <div class="col-lg-6 mb-5 mb-lg-0">
              <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('images/bg_1.jpg');">
                <div class="banner-1-inner align-self-center">
                  <h2>Pharma Products</h2>
                  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                  </p>
                </div>
              </a>
            </div>
            <div class="col-lg-6 mb-5 mb-lg-0">
              <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('images/bg_2.jpg');">
                <div class="banner-1-inner ml-auto  align-self-center">
                  <h2>Rated by Experts</h2>
                  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/navbar.html
<div class="site-navbar bg-primary py-2">
    <div class="search-wrap">
      <div class="container">
        <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
        <form action="#" method="post">
          <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
        </form>
      </div>
    </div>

    <div class="container">
      <div class="d-flex align-items-center justify-content-between">
        <div class="logo">
          <div class="site-logo">
            <a href="/" class="js-logo-clone">EPharma</a>
          </div>
        </div>
        <div class="main-nav d-none d-lg-block">
          <nav class="site-navigation text-right text-md-center" role="navigation">
            <ul class="site-menu js-clone-nav d-none d-lg-block">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="{% url 'mainweb:shop' %}">Store</a></li>
              <li><a href="{% url 'mainweb:aboutus' %}">About</a></li>
              <li><a href="{% url 'mainweb:contact' %}">Contact</a></li>
            </ul>
          </nav>
        </div>
        <div class="icons">
          <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
          <a href="cart.html" class="icons-btn d-inline-block bag">
            <span class="icon-shopping-bag"></span>
            <span class="number">2</span>
          </a>
          <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
              class="icon-menu"></span></a>
        </div>
      </div>
    </div>
  </div>